steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/viraa-care:latest', '.']
  
  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/viraa-care:latest']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'viraa-care'
      - '--image'
      - 'gcr.io/$PROJECT_ID/viraa-care:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'GOOGLE_API_KEY=AIzaSyB7x3Sym1jSqVQpitXMRRLxLszkkPo4VV4'

# Store the image in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/viraa-care:latest'

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY 